-- RW's verdict: the day rows of RW, RW-E's replay and RW-X's replay with each row's detail.perMarket, the three states'
-- clocks and checks, read-only, once after 2026-10-09 00:05 UTC. The reply is cut out with scripts/grab_payload.py into
-- data/days.json (its `pad` dropped: it only keeps the reply out of the connector's inline view).
select jsonb_build_object('pad', repeat('x', 150000), 'queried', now(),
 'rw', (select jsonb_agg(jsonb_build_object('day', day, 'total', total, 'stress_total', stress_total, 'reward', reward, 'fills', fills, 'capital', capital, 'markets', markets, 'closed_at', closed_at, 'phase', detail->>'phase', 'perMarket', detail->'perMarket') order by day) from public.pm_rw_days),
 'e', (select jsonb_agg(jsonb_build_object('day', day, 'arm', arm, 'total', total, 'stress_total', stress_total, 'reward', reward, 'fills', fills, 'capital', capital, 'markets', markets, 'closed_at', closed_at, 'perMarket', detail->'perMarket', 'check', detail->'check') order by arm, day) from public.pm_rw_e_days),
 'x', (select jsonb_agg(jsonb_build_object('day', day, 'arm', arm, 'total', total, 'stress_total', stress_total, 'reward', reward, 'fills', fills, 'capital', capital, 'markets', markets, 'closed_at', closed_at, 'perMarket', detail->'perMarket', 'check', detail->'check', 'checkE', detail->'checkE') order by arm, day) from public.pm_rw_x_days),
 'eState', (select jsonb_build_object('last_minute', last_minute, 'updated_at', updated_at, 'last_error', last_error, 'checkMaxUsd', state->'checkMaxUsd', 'version', state->'version', 'lastDecided', state->'lastDecided', 'dayOf', state->'dayOf') from public.pm_rw_e_state),
 'xState', (select jsonb_build_object('last_minute', last_minute, 'updated_at', updated_at, 'last_error', last_error, 'checkMaxUsd', state->'checkMaxUsd', 'checkEMaxUsd', state->'checkEMaxUsd', 'checkEDays', state->'checkEDays', 'version', state->'version', 'lastDecided', state->'lastDecided', 'dayOf', state->'dayOf', 'arms', (select jsonb_object_agg(k, jsonb_build_object('start', v->'start', 'diverged', jsonb_array_length(coalesce(v->'diverged','[]'::jsonb)), 'baseEmpty', (v->'base')::text = '{}')) from jsonb_each(state->'arms') t(k,v))) from public.pm_rw_x_state),
 'rwState', (select jsonb_build_object('last_minute', last_minute, 'updated_at', updated_at, 'last_error', last_error, 'dayOf', state->'dayOf', 'lastDecided', state->'lastDecided') from public.pm_rw_state)
) payload
