// The measured bands of Jev's answers to the v2 question, for JEV-DRIFT (reviews/2026-09-28-jev-drift-monitor.md): for
// each entry state a row can ask about, the lowest and highest of the five `healthy` replies measured on 2026-09-23
// through the read-only `POST ?action=jev`. A copy of `docs/agents/backtests/jev_answers_v2.json` (trend-4h, so also
// the live row) and `jev_answers_v2_other.json` (trend-1h, momentum-1d), because the Edge bundle cannot read docs/;
// jev_bands.test.ts rebuilds it from those files and fails on any difference.

export type JevBandKind = "trend-4h" | "trend-1h" | "momentum-1d";
/** How far outside its measured replies an answer may fall before it is flagged. */
export const JEV_DRIFT_MARGIN = 0.02;

/** [lowest, highest] measured reply per state. trend-4h: symbol|trend_strength|volatility|momentum_30d; the others add
 * trend_4h after the symbol and breakout_4h after trend_strength. */
export const JEV_BANDS: Record<JevBandKind, Record<string, readonly [number, number]>> = {
  "trend-4h": {
    "AVAX/USD|moderate|high|positive": [0.54, 0.56],
    "AVAX/USD|moderate|high|unknown": [0.5, 0.53],
    "AVAX/USD|moderate|low|positive": [0.7, 0.71],
    "AVAX/USD|moderate|low|unknown": [0.65, 0.67],
    "AVAX/USD|moderate|normal|positive": [0.72, 0.75],
    "AVAX/USD|moderate|normal|unknown": [0.68, 0.69],
    "AVAX/USD|strong|high|positive": [0.59, 0.61],
    "AVAX/USD|strong|high|unknown": [0.56, 0.59],
    "AVAX/USD|strong|low|positive": [0.77, 0.8],
    "AVAX/USD|strong|low|unknown": [0.73, 0.75],
    "AVAX/USD|strong|normal|positive": [0.78, 0.8],
    "AVAX/USD|strong|normal|unknown": [0.74, 0.76],
    "AVAX/USD|weak|high|positive": [0.39, 0.41],
    "AVAX/USD|weak|high|unknown": [0.36, 0.37],
    "AVAX/USD|weak|low|positive": [0.51, 0.55],
    "AVAX/USD|weak|low|unknown": [0.47, 0.48],
    "AVAX/USD|weak|normal|positive": [0.53, 0.56],
    "AVAX/USD|weak|normal|unknown": [0.48, 0.5],
    "BTC/USD|moderate|high|positive": [0.53, 0.56],
    "BTC/USD|moderate|high|unknown": [0.5, 0.51],
    "BTC/USD|moderate|low|positive": [0.71, 0.73],
    "BTC/USD|moderate|low|unknown": [0.66, 0.68],
    "BTC/USD|moderate|normal|positive": [0.74, 0.75],
    "BTC/USD|moderate|normal|unknown": [0.68, 0.69],
    "BTC/USD|strong|high|positive": [0.57, 0.6],
    "BTC/USD|strong|high|unknown": [0.54, 0.57],
    "BTC/USD|strong|low|positive": [0.75, 0.78],
    "BTC/USD|strong|low|unknown": [0.71, 0.75],
    "BTC/USD|strong|normal|positive": [0.77, 0.79],
    "BTC/USD|strong|normal|unknown": [0.73, 0.75],
    "BTC/USD|weak|high|positive": [0.38, 0.4],
    "BTC/USD|weak|high|unknown": [0.36, 0.38],
    "BTC/USD|weak|low|positive": [0.54, 0.56],
    "BTC/USD|weak|low|unknown": [0.48, 0.5],
    "BTC/USD|weak|normal|positive": [0.54, 0.57],
    "BTC/USD|weak|normal|unknown": [0.48, 0.51],
    "ETH/USD|moderate|high|positive": [0.53, 0.54],
    "ETH/USD|moderate|high|unknown": [0.49, 0.51],
    "ETH/USD|moderate|low|positive": [0.7, 0.72],
    "ETH/USD|moderate|low|unknown": [0.65, 0.67],
    "ETH/USD|moderate|normal|positive": [0.73, 0.75],
    "ETH/USD|moderate|normal|unknown": [0.68, 0.7],
    "ETH/USD|strong|high|positive": [0.58, 0.62],
    "ETH/USD|strong|high|unknown": [0.56, 0.58],
    "ETH/USD|strong|low|positive": [0.76, 0.78],
    "ETH/USD|strong|low|unknown": [0.72, 0.75],
    "ETH/USD|strong|normal|positive": [0.77, 0.78],
    "ETH/USD|strong|normal|unknown": [0.73, 0.75],
    "ETH/USD|weak|high|positive": [0.38, 0.4],
    "ETH/USD|weak|high|unknown": [0.35, 0.38],
    "ETH/USD|weak|low|positive": [0.52, 0.54],
    "ETH/USD|weak|low|unknown": [0.47, 0.49],
    "ETH/USD|weak|normal|positive": [0.53, 0.57],
    "ETH/USD|weak|normal|unknown": [0.47, 0.49],
    "SOL/USD|moderate|high|positive": [0.53, 0.55],
    "SOL/USD|moderate|high|unknown": [0.49, 0.52],
    "SOL/USD|moderate|low|positive": [0.71, 0.72],
    "SOL/USD|moderate|low|unknown": [0.65, 0.67],
    "SOL/USD|moderate|normal|positive": [0.73, 0.74],
    "SOL/USD|moderate|normal|unknown": [0.66, 0.7],
    "SOL/USD|strong|high|positive": [0.58, 0.61],
    "SOL/USD|strong|high|unknown": [0.55, 0.58],
    "SOL/USD|strong|low|positive": [0.76, 0.77],
    "SOL/USD|strong|low|unknown": [0.72, 0.74],
    "SOL/USD|strong|normal|positive": [0.78, 0.79],
    "SOL/USD|strong|normal|unknown": [0.74, 0.75],
    "SOL/USD|weak|high|positive": [0.38, 0.41],
    "SOL/USD|weak|high|unknown": [0.36, 0.38],
    "SOL/USD|weak|low|positive": [0.52, 0.53],
    "SOL/USD|weak|low|unknown": [0.47, 0.49],
    "SOL/USD|weak|normal|positive": [0.53, 0.54],
    "SOL/USD|weak|normal|unknown": [0.48, 0.51],
    "SUI/USD|moderate|high|positive": [0.52, 0.54],
    "SUI/USD|moderate|high|unknown": [0.49, 0.51],
    "SUI/USD|moderate|low|positive": [0.7, 0.71],
    "SUI/USD|moderate|low|unknown": [0.64, 0.66],
    "SUI/USD|moderate|normal|positive": [0.71, 0.74],
    "SUI/USD|moderate|normal|unknown": [0.67, 0.69],
    "SUI/USD|strong|high|positive": [0.57, 0.59],
    "SUI/USD|strong|high|unknown": [0.54, 0.57],
    "SUI/USD|strong|low|positive": [0.76, 0.78],
    "SUI/USD|strong|low|unknown": [0.74, 0.76],
    "SUI/USD|strong|normal|positive": [0.78, 0.79],
    "SUI/USD|strong|normal|unknown": [0.73, 0.74],
    "SUI/USD|weak|high|positive": [0.38, 0.4],
    "SUI/USD|weak|high|unknown": [0.36, 0.37],
    "SUI/USD|weak|low|positive": [0.52, 0.55],
    "SUI/USD|weak|low|unknown": [0.48, 0.49],
    "SUI/USD|weak|normal|positive": [0.54, 0.54],
    "SUI/USD|weak|normal|unknown": [0.47, 0.49],
  },
  "trend-1h": {
    "BTC/USD|up|moderate|above_range|high|positive": [0.53, 0.57],
    "BTC/USD|up|moderate|above_range|high|unknown": [0.51, 0.53],
    "BTC/USD|up|moderate|above_range|low|positive": [0.71, 0.72],
    "BTC/USD|up|moderate|above_range|low|unknown": [0.66, 0.69],
    "BTC/USD|up|moderate|above_range|normal|positive": [0.73, 0.75],
    "BTC/USD|up|moderate|above_range|normal|unknown": [0.69, 0.71],
    "BTC/USD|up|strong|above_range|high|positive": [0.58, 0.6],
    "BTC/USD|up|strong|above_range|high|unknown": [0.56, 0.59],
    "BTC/USD|up|strong|above_range|low|positive": [0.77, 0.78],
    "BTC/USD|up|strong|above_range|low|unknown": [0.71, 0.73],
    "BTC/USD|up|strong|above_range|normal|positive": [0.78, 0.79],
    "BTC/USD|up|strong|above_range|normal|unknown": [0.73, 0.76],
    "BTC/USD|up|weak|above_range|high|positive": [0.4, 0.41],
    "BTC/USD|up|weak|above_range|high|unknown": [0.38, 0.38],
    "BTC/USD|up|weak|above_range|low|positive": [0.54, 0.56],
    "BTC/USD|up|weak|above_range|low|unknown": [0.48, 0.5],
    "BTC/USD|up|weak|above_range|normal|positive": [0.54, 0.57],
    "BTC/USD|up|weak|above_range|normal|unknown": [0.5, 0.52],
    "ETH/USD|up|moderate|above_range|high|positive": [0.52, 0.56],
    "ETH/USD|up|moderate|above_range|high|unknown": [0.51, 0.53],
    "ETH/USD|up|moderate|above_range|low|positive": [0.71, 0.72],
    "ETH/USD|up|moderate|above_range|low|unknown": [0.66, 0.67],
    "ETH/USD|up|moderate|above_range|normal|positive": [0.74, 0.75],
    "ETH/USD|up|moderate|above_range|normal|unknown": [0.69, 0.71],
    "ETH/USD|up|strong|above_range|high|positive": [0.57, 0.63],
    "ETH/USD|up|strong|above_range|high|unknown": [0.54, 0.59],
    "ETH/USD|up|strong|above_range|low|positive": [0.74, 0.78],
    "ETH/USD|up|strong|above_range|low|unknown": [0.74, 0.74],
    "ETH/USD|up|strong|above_range|normal|positive": [0.78, 0.79],
    "ETH/USD|up|strong|above_range|normal|unknown": [0.74, 0.76],
    "ETH/USD|up|weak|above_range|high|positive": [0.4, 0.41],
    "ETH/USD|up|weak|above_range|high|unknown": [0.38, 0.39],
    "ETH/USD|up|weak|above_range|low|positive": [0.53, 0.56],
    "ETH/USD|up|weak|above_range|low|unknown": [0.47, 0.49],
    "ETH/USD|up|weak|above_range|normal|positive": [0.54, 0.57],
    "ETH/USD|up|weak|above_range|normal|unknown": [0.5, 0.52],
    "SOL/USD|up|moderate|above_range|high|positive": [0.54, 0.57],
    "SOL/USD|up|moderate|above_range|high|unknown": [0.52, 0.54],
    "SOL/USD|up|moderate|above_range|low|positive": [0.71, 0.72],
    "SOL/USD|up|moderate|above_range|low|unknown": [0.66, 0.68],
    "SOL/USD|up|moderate|above_range|normal|positive": [0.74, 0.75],
    "SOL/USD|up|moderate|above_range|normal|unknown": [0.68, 0.71],
    "SOL/USD|up|strong|above_range|high|positive": [0.6, 0.61],
    "SOL/USD|up|strong|above_range|high|unknown": [0.59, 0.61],
    "SOL/USD|up|strong|above_range|low|positive": [0.77, 0.78],
    "SOL/USD|up|strong|above_range|low|unknown": [0.73, 0.75],
    "SOL/USD|up|strong|above_range|normal|positive": [0.78, 0.8],
    "SOL/USD|up|strong|above_range|normal|unknown": [0.74, 0.76],
    "SOL/USD|up|weak|above_range|high|positive": [0.4, 0.41],
    "SOL/USD|up|weak|above_range|high|unknown": [0.37, 0.4],
    "SOL/USD|up|weak|above_range|low|positive": [0.53, 0.56],
    "SOL/USD|up|weak|above_range|low|unknown": [0.48, 0.49],
    "SOL/USD|up|weak|above_range|normal|positive": [0.55, 0.57],
    "SOL/USD|up|weak|above_range|normal|unknown": [0.49, 0.51],
  },
  "momentum-1d": {
    "BTC/USD|down|moderate|above_range|high|positive": [0.31, 0.33],
    "BTC/USD|down|moderate|above_range|low|positive": [0.4, 0.42],
    "BTC/USD|down|moderate|above_range|normal|positive": [0.4, 0.42],
    "BTC/USD|down|moderate|below_range|high|positive": [0.2, 0.21],
    "BTC/USD|down|moderate|below_range|low|positive": [0.24, 0.26],
    "BTC/USD|down|moderate|below_range|normal|positive": [0.23, 0.25],
    "BTC/USD|down|moderate|inside_range|high|positive": [0.22, 0.23],
    "BTC/USD|down|moderate|inside_range|low|positive": [0.25, 0.28],
    "BTC/USD|down|moderate|inside_range|normal|positive": [0.25, 0.27],
    "BTC/USD|down|strong|above_range|high|positive": [0.23, 0.25],
    "BTC/USD|down|strong|above_range|low|positive": [0.28, 0.32],
    "BTC/USD|down|strong|above_range|normal|positive": [0.28, 0.31],
    "BTC/USD|down|strong|below_range|high|positive": [0.16, 0.17],
    "BTC/USD|down|strong|below_range|low|positive": [0.19, 0.21],
    "BTC/USD|down|strong|below_range|normal|positive": [0.2, 0.2],
    "BTC/USD|down|strong|inside_range|high|positive": [0.17, 0.19],
    "BTC/USD|down|strong|inside_range|low|positive": [0.21, 0.22],
    "BTC/USD|down|strong|inside_range|normal|positive": [0.2, 0.22],
    "BTC/USD|down|weak|above_range|high|positive": [0.36, 0.39],
    "BTC/USD|down|weak|above_range|low|positive": [0.47, 0.5],
    "BTC/USD|down|weak|above_range|normal|positive": [0.47, 0.5],
    "BTC/USD|down|weak|below_range|high|positive": [0.22, 0.23],
    "BTC/USD|down|weak|below_range|low|positive": [0.27, 0.28],
    "BTC/USD|down|weak|below_range|normal|positive": [0.27, 0.28],
    "BTC/USD|down|weak|inside_range|high|positive": [0.25, 0.26],
    "BTC/USD|down|weak|inside_range|low|positive": [0.31, 0.32],
    "BTC/USD|down|weak|inside_range|normal|positive": [0.3, 0.33],
    "BTC/USD|flat|weak|above_range|high|positive": [0.4, 0.42],
    "BTC/USD|flat|weak|above_range|low|positive": [0.51, 0.55],
    "BTC/USD|flat|weak|above_range|normal|positive": [0.53, 0.54],
    "BTC/USD|flat|weak|below_range|high|positive": [0.22, 0.23],
    "BTC/USD|flat|weak|below_range|low|positive": [0.29, 0.3],
    "BTC/USD|flat|weak|below_range|normal|positive": [0.28, 0.3],
    "BTC/USD|flat|weak|inside_range|high|positive": [0.27, 0.28],
    "BTC/USD|flat|weak|inside_range|low|positive": [0.34, 0.35],
    "BTC/USD|flat|weak|inside_range|normal|positive": [0.33, 0.35],
    "BTC/USD|up|moderate|above_range|high|positive": [0.54, 0.56],
    "BTC/USD|up|moderate|above_range|low|positive": [0.71, 0.72],
    "BTC/USD|up|moderate|above_range|normal|positive": [0.74, 0.75],
    "BTC/USD|up|moderate|below_range|high|positive": [0.34, 0.35],
    "BTC/USD|up|moderate|below_range|low|positive": [0.42, 0.43],
    "BTC/USD|up|moderate|below_range|normal|positive": [0.43, 0.44],
    "BTC/USD|up|moderate|inside_range|high|positive": [0.4, 0.42],
    "BTC/USD|up|moderate|inside_range|low|positive": [0.48, 0.51],
    "BTC/USD|up|moderate|inside_range|normal|positive": [0.52, 0.54],
    "BTC/USD|up|strong|above_range|high|positive": [0.58, 0.61],
    "BTC/USD|up|strong|above_range|low|positive": [0.78, 0.8],
    "BTC/USD|up|strong|above_range|normal|positive": [0.78, 0.81],
    "BTC/USD|up|strong|below_range|high|positive": [0.35, 0.37],
    "BTC/USD|up|strong|below_range|low|positive": [0.44, 0.46],
    "BTC/USD|up|strong|below_range|normal|positive": [0.44, 0.46],
    "BTC/USD|up|strong|inside_range|high|positive": [0.48, 0.49],
    "BTC/USD|up|strong|inside_range|low|positive": [0.55, 0.6],
    "BTC/USD|up|strong|inside_range|normal|positive": [0.6, 0.6],
    "BTC/USD|up|weak|above_range|high|positive": [0.42, 0.44],
    "BTC/USD|up|weak|above_range|low|positive": [0.59, 0.59],
    "BTC/USD|up|weak|above_range|normal|positive": [0.59, 0.61],
    "BTC/USD|up|weak|below_range|high|positive": [0.26, 0.28],
    "BTC/USD|up|weak|below_range|low|positive": [0.32, 0.34],
    "BTC/USD|up|weak|below_range|normal|positive": [0.33, 0.35],
    "BTC/USD|up|weak|inside_range|high|positive": [0.3, 0.32],
    "BTC/USD|up|weak|inside_range|low|positive": [0.38, 0.4],
    "BTC/USD|up|weak|inside_range|normal|positive": [0.39, 0.4],
    "ETH/USD|down|moderate|above_range|high|positive": [0.32, 0.33],
    "ETH/USD|down|moderate|above_range|low|positive": [0.38, 0.4],
    "ETH/USD|down|moderate|above_range|normal|positive": [0.39, 0.41],
    "ETH/USD|down|moderate|below_range|high|positive": [0.21, 0.22],
    "ETH/USD|down|moderate|below_range|low|positive": [0.25, 0.27],
    "ETH/USD|down|moderate|below_range|normal|positive": [0.24, 0.25],
    "ETH/USD|down|moderate|inside_range|high|positive": [0.22, 0.23],
    "ETH/USD|down|moderate|inside_range|low|positive": [0.26, 0.27],
    "ETH/USD|down|moderate|inside_range|normal|positive": [0.26, 0.27],
    "ETH/USD|down|strong|above_range|high|positive": [0.24, 0.26],
    "ETH/USD|down|strong|above_range|low|positive": [0.29, 0.31],
    "ETH/USD|down|strong|above_range|normal|positive": [0.29, 0.31],
    "ETH/USD|down|strong|below_range|high|positive": [0.16, 0.17],
    "ETH/USD|down|strong|below_range|low|positive": [0.2, 0.2],
    "ETH/USD|down|strong|below_range|normal|positive": [0.2, 0.2],
    "ETH/USD|down|strong|inside_range|high|positive": [0.18, 0.19],
    "ETH/USD|down|strong|inside_range|low|positive": [0.21, 0.22],
    "ETH/USD|down|strong|inside_range|normal|positive": [0.21, 0.22],
    "ETH/USD|down|weak|above_range|high|positive": [0.37, 0.39],
    "ETH/USD|down|weak|above_range|low|positive": [0.46, 0.48],
    "ETH/USD|down|weak|above_range|normal|positive": [0.47, 0.5],
    "ETH/USD|down|weak|below_range|high|positive": [0.22, 0.24],
    "ETH/USD|down|weak|below_range|low|positive": [0.27, 0.29],
    "ETH/USD|down|weak|below_range|normal|positive": [0.27, 0.29],
    "ETH/USD|down|weak|inside_range|high|positive": [0.25, 0.27],
    "ETH/USD|down|weak|inside_range|low|positive": [0.3, 0.32],
    "ETH/USD|down|weak|inside_range|normal|positive": [0.3, 0.33],
    "ETH/USD|flat|weak|above_range|high|positive": [0.4, 0.41],
    "ETH/USD|flat|weak|above_range|low|positive": [0.51, 0.53],
    "ETH/USD|flat|weak|above_range|normal|positive": [0.51, 0.54],
    "ETH/USD|flat|weak|below_range|high|positive": [0.23, 0.24],
    "ETH/USD|flat|weak|below_range|low|positive": [0.29, 0.3],
    "ETH/USD|flat|weak|below_range|normal|positive": [0.29, 0.3],
    "ETH/USD|flat|weak|inside_range|high|positive": [0.27, 0.29],
    "ETH/USD|flat|weak|inside_range|low|positive": [0.33, 0.33],
    "ETH/USD|flat|weak|inside_range|normal|positive": [0.33, 0.34],
    "ETH/USD|up|moderate|above_range|high|positive": [0.55, 0.57],
    "ETH/USD|up|moderate|above_range|low|positive": [0.71, 0.73],
    "ETH/USD|up|moderate|above_range|normal|positive": [0.74, 0.76],
    "ETH/USD|up|moderate|below_range|high|positive": [0.34, 0.35],
    "ETH/USD|up|moderate|below_range|low|positive": [0.42, 0.45],
    "ETH/USD|up|moderate|below_range|normal|positive": [0.43, 0.46],
    "ETH/USD|up|moderate|inside_range|high|positive": [0.41, 0.42],
    "ETH/USD|up|moderate|inside_range|low|positive": [0.5, 0.53],
    "ETH/USD|up|moderate|inside_range|normal|positive": [0.52, 0.56],
    "ETH/USD|up|strong|above_range|high|positive": [0.6, 0.62],
    "ETH/USD|up|strong|above_range|low|positive": [0.78, 0.8],
    "ETH/USD|up|strong|above_range|normal|positive": [0.79, 0.81],
    "ETH/USD|up|strong|below_range|high|positive": [0.37, 0.39],
    "ETH/USD|up|strong|below_range|low|positive": [0.45, 0.48],
    "ETH/USD|up|strong|below_range|normal|positive": [0.45, 0.49],
    "ETH/USD|up|strong|inside_range|high|positive": [0.48, 0.5],
    "ETH/USD|up|strong|inside_range|low|positive": [0.56, 0.59],
    "ETH/USD|up|strong|inside_range|normal|positive": [0.58, 0.62],
    "ETH/USD|up|weak|above_range|high|positive": [0.43, 0.44],
    "ETH/USD|up|weak|above_range|low|positive": [0.56, 0.59],
    "ETH/USD|up|weak|above_range|normal|positive": [0.59, 0.6],
    "ETH/USD|up|weak|below_range|high|positive": [0.25, 0.26],
    "ETH/USD|up|weak|below_range|low|positive": [0.32, 0.34],
    "ETH/USD|up|weak|below_range|normal|positive": [0.33, 0.35],
    "ETH/USD|up|weak|inside_range|high|positive": [0.3, 0.32],
    "ETH/USD|up|weak|inside_range|low|positive": [0.38, 0.39],
    "ETH/USD|up|weak|inside_range|normal|positive": [0.37, 0.39],
    "SOL/USD|down|moderate|above_range|high|positive": [0.32, 0.34],
    "SOL/USD|down|moderate|above_range|low|positive": [0.39, 0.42],
    "SOL/USD|down|moderate|above_range|normal|positive": [0.4, 0.41],
    "SOL/USD|down|moderate|below_range|high|positive": [0.2, 0.21],
    "SOL/USD|down|moderate|below_range|low|positive": [0.24, 0.25],
    "SOL/USD|down|moderate|below_range|normal|positive": [0.23, 0.24],
    "SOL/USD|down|moderate|inside_range|high|positive": [0.22, 0.23],
    "SOL/USD|down|moderate|inside_range|low|positive": [0.25, 0.27],
    "SOL/USD|down|moderate|inside_range|normal|positive": [0.26, 0.26],
    "SOL/USD|down|strong|above_range|high|positive": [0.25, 0.27],
    "SOL/USD|down|strong|above_range|low|positive": [0.31, 0.33],
    "SOL/USD|down|strong|above_range|normal|positive": [0.31, 0.34],
    "SOL/USD|down|strong|below_range|high|positive": [0.16, 0.17],
    "SOL/USD|down|strong|below_range|low|positive": [0.19, 0.2],
    "SOL/USD|down|strong|below_range|normal|positive": [0.19, 0.21],
    "SOL/USD|down|strong|inside_range|high|positive": [0.17, 0.19],
    "SOL/USD|down|strong|inside_range|low|positive": [0.21, 0.21],
    "SOL/USD|down|strong|inside_range|normal|positive": [0.2, 0.21],
    "SOL/USD|down|weak|above_range|high|positive": [0.36, 0.39],
    "SOL/USD|down|weak|above_range|low|positive": [0.47, 0.48],
    "SOL/USD|down|weak|above_range|normal|positive": [0.45, 0.49],
    "SOL/USD|down|weak|below_range|high|positive": [0.22, 0.23],
    "SOL/USD|down|weak|below_range|low|positive": [0.26, 0.29],
    "SOL/USD|down|weak|below_range|normal|positive": [0.27, 0.28],
    "SOL/USD|down|weak|inside_range|high|positive": [0.24, 0.26],
    "SOL/USD|down|weak|inside_range|low|positive": [0.29, 0.3],
    "SOL/USD|down|weak|inside_range|normal|positive": [0.29, 0.31],
    "SOL/USD|flat|weak|above_range|high|positive": [0.4, 0.41],
    "SOL/USD|flat|weak|above_range|low|positive": [0.52, 0.54],
    "SOL/USD|flat|weak|above_range|normal|positive": [0.51, 0.54],
    "SOL/USD|flat|weak|below_range|high|positive": [0.24, 0.24],
    "SOL/USD|flat|weak|below_range|low|positive": [0.28, 0.31],
    "SOL/USD|flat|weak|below_range|normal|positive": [0.29, 0.31],
    "SOL/USD|flat|weak|inside_range|high|positive": [0.28, 0.29],
    "SOL/USD|flat|weak|inside_range|low|positive": [0.33, 0.34],
    "SOL/USD|flat|weak|inside_range|normal|positive": [0.33, 0.35],
    "SOL/USD|up|moderate|above_range|high|positive": [0.55, 0.58],
    "SOL/USD|up|moderate|above_range|low|positive": [0.72, 0.73],
    "SOL/USD|up|moderate|above_range|normal|positive": [0.75, 0.75],
    "SOL/USD|up|moderate|below_range|high|positive": [0.34, 0.36],
    "SOL/USD|up|moderate|below_range|low|positive": [0.42, 0.45],
    "SOL/USD|up|moderate|below_range|normal|positive": [0.43, 0.46],
    "SOL/USD|up|moderate|inside_range|high|positive": [0.4, 0.43],
    "SOL/USD|up|moderate|inside_range|low|positive": [0.48, 0.51],
    "SOL/USD|up|moderate|inside_range|normal|positive": [0.52, 0.55],
    "SOL/USD|up|strong|above_range|high|positive": [0.59, 0.63],
    "SOL/USD|up|strong|above_range|low|positive": [0.78, 0.81],
    "SOL/USD|up|strong|above_range|normal|positive": [0.79, 0.81],
    "SOL/USD|up|strong|below_range|high|positive": [0.35, 0.38],
    "SOL/USD|up|strong|below_range|low|positive": [0.45, 0.47],
    "SOL/USD|up|strong|below_range|normal|positive": [0.44, 0.47],
    "SOL/USD|up|strong|inside_range|high|positive": [0.47, 0.49],
    "SOL/USD|up|strong|inside_range|low|positive": [0.58, 0.6],
    "SOL/USD|up|strong|inside_range|normal|positive": [0.6, 0.63],
    "SOL/USD|up|weak|above_range|high|positive": [0.43, 0.44],
    "SOL/USD|up|weak|above_range|low|positive": [0.58, 0.6],
    "SOL/USD|up|weak|above_range|normal|positive": [0.59, 0.61],
    "SOL/USD|up|weak|below_range|high|positive": [0.25, 0.27],
    "SOL/USD|up|weak|below_range|low|positive": [0.33, 0.35],
    "SOL/USD|up|weak|below_range|normal|positive": [0.32, 0.34],
    "SOL/USD|up|weak|inside_range|high|positive": [0.3, 0.32],
    "SOL/USD|up|weak|inside_range|low|positive": [0.37, 0.39],
    "SOL/USD|up|weak|inside_range|normal|positive": [0.38, 0.4],
  },
};

/** A state's key in `JEV_BANDS[kind]`, from the categorical state a decision records. */
export function jevBandKey(kind: JevBandKind, st: Record<string, unknown>): string {
  const f = (k: string) => String(st[k] ?? "");
  return kind === "trend-4h"
    ? [f("symbol"), f("trend_strength"), f("volatility"), f("momentum_30d")].join("|")
    : [f("symbol"), f("trend_4h"), f("trend_strength"), f("breakout_4h"), f("volatility"), f("momentum_30d")].join("|");
}

export type JevBand = { key: string; min: number | null; max: number | null; inBand: boolean };

/**
 * JEV-DRIFT's check on one entry's answer: its state's measured band, widened by `JEV_DRIFT_MARGIN` either side, and
 * whether the answer lies inside it. Null for a row kind that has no measured bands (nothing to check). A state that was
 * never measured comes back with no band and `inBand: false`: it is a flag in itself.
 */
export function jevBandCheck(kind: string, st: Record<string, unknown>, p: number): JevBand | null {
  if (kind !== "trend-4h" && kind !== "trend-1h" && kind !== "momentum-1d") return null;
  const key = jevBandKey(kind, st);
  const b = JEV_BANDS[kind][key];
  if (!b) return { key, min: null, max: null, inBand: false };
  const min = Math.round((b[0] - JEV_DRIFT_MARGIN) * 100) / 100, max = Math.round((b[1] + JEV_DRIFT_MARGIN) * 100) / 100;
  return { key, min, max, inBand: p >= min - 1e-9 && p <= max + 1e-9 };
}
