-- LP-ALLOC: live-prep's live day 2026-10-09, read-only, for the calibration (scripts/calib.py). Three statements, each
-- padded so the connector saves its reply; scripts/grab.py cuts the payload out and drops the pad.
-- 1. data/lp_minutes_live_1009.json: every live minute: cond, minute (epoch s), the selection's rate, max spread and
--    minimum, the formula as the path computed it, Polymarket's order-scoring per side (1/0, -1 unread), its pct, our sizes,
--    our two sides' scores.
select jsonb_build_object('pad', repeat('x', 100000), 'minutes', (select string_agg(concat_ws(',', left(cond, 66), extract(epoch from minute)::bigint, rate, max_spread, min_size, coalesce(formula_usd, 0), coalesce(bid_scoring::int, -1), coalesce(ask_scoring::int, -1), coalesce(pct, -1), coalesce(bid_size,0), coalesce(ask_size,0), coalesce((detail->>'qBid')::numeric, 0), coalesce((detail->>'qAsk')::numeric, 0)), ';' order by minute, cond) from public.pm_lp_minutes where mode='live' and minute >= '2026-10-09' and minute < '2026-10-10')) payload;
-- 2. data/lp_live_1009.json: the day's fills (CONFIRMED, by match time) and the selections of 10-09 and 10-10.
select jsonb_build_object('pad', repeat('x', 120000), 'fills', (select jsonb_agg(jsonb_build_object('cond', f.cond, 'outcome', case when f.token = m.yes_token then 'yes' when f.token = m.no_token then 'no' else '?' end, 'side', f.side, 'price', f.price, 'size', f.size, 't', f.match_time, 'status', f.status) order by f.match_time) from public.pm_lp_fills f left join lateral (select yes_token, no_token from public.pm_lp_markets x where x.cond = f.cond order by day desc limit 1) m on true where f.match_time >= '2026-10-09' and f.match_time < '2026-10-10'), 'markets', (select jsonb_agg(jsonb_build_object('day', day, 'cond', cond, 'kind', kind, 'rank', rank, 'rate', reward_rate, 'min_size', min_size, 'max_spread', max_spread, 'n', n_size, 'capital', capital, 'formula_day', formula_day, 'selected_at', selected_at)) from public.pm_lp_markets where day >= '2026-10-09')) payload;
-- 3. data/aux.json: ../../lpself/sql/aux.sql as it is (sql/aux.sql here).
