-- 0038: retire the dislocation-1m paper strategy.
--
-- The 1-minute study that suggested an edge here measured stale
-- last-trade prints, not quotes (docs/agents/reference.md §3.5). Read
-- against the live touch the rule waited seven hours, then fired once,
-- at 01:26 UTC on 2026-09-21, and lost 68 bps all-in inside a minute.
-- That trade was not even a trade this account could have made: Revolut
-- X publishes two books per pair (region UK / EEA) and the venue client
-- kept whichever ticker row came last, so the "cheap" ask it lifted and
-- the bid its stop hit were the EEA book's — thin that night — while the
-- UK book this account trades on sat 0.1–6 bps wide. The region fix is
-- the commit after this one. Davies had already asked for the rule to
-- go rather than sit on the page doing nothing. The rulebook stays in the
-- code and its tests; `agent_basis` keeps being written every fifth
-- minute, because the "no arbitrage" evidence is worth keeping (rows
-- before the fix mix the two books).
--
-- Only the strategy row goes. Its decisions, orders and observations stay
-- as the record of what it saw and did (nothing references a strategy row
-- by foreign key; the dashboard and the tick read those tables per
-- strategy that exists, so the rows are inert, and the retention prune
-- ages them out with everything else).

delete from public.agent_strategies where id = 'dislocation-1m';
