-- 0072: "Stablecoin quotes variant-2" (rule D) on paper, beside PR5V
-- (reference §4 item 47; its pre-registration, `reviews/2026-09-28-pr5-rule-d-prereg.md`).
--
-- Davies, 2026-09-28: rule D goes on paper as variant-2. It is a second instance of PR5V's decision function, with its
-- own state, tables, lease and cron row. PR5V's row of this job, its tables and its code version are not rewritten.
-- Arm `d` is judged: PR5V's nine rungs, with entries re-priced at max(0.03 %, k/3), and TrueFX's GBP/USD on a minute
-- the call is deciding within three minutes of its clock (Yahoo, the bar PR5 stored, otherwise). Arm `v1` is the
-- deviation: PR5V's own settings on PR5's stored X, so a drift in the shared function shows up here.
--
-- `agents?action=quotesd` (`agents/quotes_ruled.ts`) decides a minute only once PR5's engine has
-- (`agent_quote_state.last_minute`, the one column of PR5's state it reads). Of PR5V it reads trips only, to store the
-- deviation check, and writes none of them. It calls no venue. Both arms start flat at 2026-09-28 00:00 UTC.
--
-- ⚠️  CROSS-ENVIRONMENT WARNING (as 0037): the job's `url` is the PRODUCTION project's Edge Function host, hardcoded.
-- Applying this to any other database makes THAT database POST to production every minute.

create table if not exists public.agent_quoted_state (
  id          integer primary key check (id = 1),
  -- Both arms, and the deviation check: the largest absolute difference of daily P&L between arm `v1` and PR5V's arm
  -- `main`, and how many days either had a trip (`state.checkMaxUsd`, `state.checkDays`).
  state       jsonb not null default '{}'::jsonb,
  last_minute timestamptz,
  updated_at  timestamptz not null default now(),
  last_error  text
);

-- What each book-minute was decided on. `x` is the rate arm `v1` used (PR5's, or rebuilt the way PR5V rebuilds).
-- `x_d` is the rate arm `d` used, and `x_source` says whether that was TrueFX or Yahoo.
create table if not exists public.agent_quoted_minutes (
  book         text not null check (book in ('USDC-GBP', 'USDT-GBP')),
  minute       timestamptz not null,
  source       text not null check (source in ('minutes', 'rebuilt')),
  x            numeric check (x is null or x > 0),
  x_t          timestamptz,
  fair_u       numeric check (fair_u is null or fair_u > 0),
  hours_n      integer not null check (hours_n >= 0),
  prints_n     integer not null check (prints_n >= 0),
  pr5_prints_n integer check (pr5_prints_n is null or pr5_prints_n >= 0),
  x_d          numeric check (x_d is null or x_d > 0),
  x_source     text not null check (x_source in ('yahoo', 'truefx')),
  recorded_at  timestamptz not null default now(),
  primary key (book, minute)
);

create table if not exists public.agent_quoted_events (
  arm    text not null check (arm in ('v1', 'd')),
  book   text not null check (book in ('USDC-GBP', 'USDT-GBP')),
  minute timestamptz not null,
  side   text not null check (side in ('bid', 'ask', '-')),
  k      numeric not null,
  kind   text not null check (kind in ('order', 'refused', 'withdraw', 'fill', 'exit', 'stop')),
  what   text,
  key    text check (key is null or key in ('USDC-GBP/bid', 'USDC-GBP/ask', 'USDT-GBP/bid', 'USDT-GBP/ask')),
  ticks  integer,
  detail jsonb not null default '{}'::jsonb,
  primary key (arm, book, minute, side, k, kind),
  constraint agent_quoted_events_what_check check (case kind
    when 'order' then coalesce(what in ('place', 'reprice', 'replace', 'exit', 'exit_reprice', 'exit_replace'), false)
    when 'stop' then coalesce(what = 'stop', false)
    else what is null end)
);

create table if not exists public.agent_quoted_trips (
  id            bigint generated by default as identity unique,
  arm           text not null check (arm in ('v1', 'd')),
  key           text not null check (key in ('USDC-GBP/bid', 'USDC-GBP/ask', 'USDT-GBP/bid', 'USDT-GBP/ask')),
  book          text not null check (book in ('USDC-GBP', 'USDT-GBP')),
  side          text not null check (side in ('bid', 'ask')),
  k             numeric not null,
  t_entry       timestamptz not null,
  fill_ts       timestamptz not null,
  fill_print_id text not null,
  entry         numeric not null check (entry > 0),
  qty           numeric not null check (qty > 0),
  x_entry       numeric,
  fair_entry    numeric,
  entry_oid     integer,
  t_exit        timestamptz not null,
  exit          numeric not null check (exit > 0),
  how           text not null check (how in ('maker', 'taker')),
  exit_print_id text,
  exit_oid      integer,
  notional_usd  numeric not null,
  pnl_usd       numeric not null,
  primary key (arm, book, side, k, t_entry)
);

alter table public.agent_quoted_state   enable row level security;
alter table public.agent_quoted_minutes enable row level security;
alter table public.agent_quoted_events  enable row level security;
alter table public.agent_quoted_trips   enable row level security;

create or replace view public.agent_quoted_days with (security_invoker = true) as
with ev as (
  select arm, (minute at time zone 'UTC')::date as day,
         count(*) filter (where kind = 'order') as orders,
         count(*) filter (where what is not null) as posts,
         count(*) filter (where kind = 'fill') as fills
  from public.agent_quoted_events
  where kind in ('order', 'stop', 'fill')
  group by 1, 2
), tr as (
  select arm, (t_exit at time zone 'UTC')::date as day,
         count(*) as trips,
         count(*) filter (where pnl_usd > 0) as won,
         sum(pnl_usd) as realised_usd
  from public.agent_quoted_trips
  group by 1, 2
)
select coalesce(ev.arm, tr.arm) as arm,
       coalesce(ev.day, tr.day) as day,
       coalesce(ev.orders, 0) as orders,
       coalesce(ev.posts, 0) as posts,
       coalesce(ev.fills, 0) as fills,
       coalesce(tr.trips, 0) as trips,
       coalesce(tr.won, 0) as won,
       coalesce(tr.realised_usd, 0) as realised_usd
from ev full outer join tr on tr.arm = ev.arm and tr.day = ev.day;

-- A code change that could change a decision bumps `RULED_CODE_VERSION` in quotes_ruled.ts; the next call then runs
-- this and decides everything again from 2026-09-28 00:00 UTC, flat. It deletes this instance's rows and nothing else.
create or replace function public.agent_quoted_reset() returns void language sql as $$
  delete from public.agent_quoted_events where true;
  delete from public.agent_quoted_trips where true;
  delete from public.agent_quoted_minutes where true;
  delete from public.agent_quoted_state where true;
$$;
revoke execute on function public.agent_quoted_reset() from public, anon, authenticated;
grant execute on function public.agent_quoted_reset() to service_role;

insert into public.agent_locks (name) values ('quotesd') on conflict (name) do nothing;

-- The one job every recurring Edge call is a row of (0063), with the list 0071 left and this call added beside
-- the variant's. It waits for nothing: it decides what PR5 has decided by the time it runs.
select cron.schedule(
  'edge-calls-every-minute',
  '* * * * *',
  $cron$
    select net.http_post(
      url     := 'https://flmvxigozjuizpckllvk.supabase.co/functions/v1/' || call.path,
      headers := jsonb_build_object(
        'Authorization',
        concat('Bearer ', (select decrypted_secret from vault.decrypted_secrets where name = 'cron_secret')),
        'Content-Type', 'application/json'
      ),
      body    := '{}'::jsonb,
      timeout_milliseconds := call.timeout_ms
    )
    from (values
      ('agents?action=tick',          50000, 1, 23),
      ('agents?action=quotes',        58000, 1, 23),
      ('agents?action=quotesv',       58000, 1, 23),
      ('agents?action=quotesd',       58000, 1, 23),
      ('agents?action=books',         58000, 1, 23),
      ('agents?action=pmrw',          58000, 1, 23),
      ('agents?action=pmrw-e',        58000, 1, 23),
      ('agents?action=pmrw-x',        58000, 1, 23),
      ('agents?action=pmrwc',         58000, 1, 23),
      ('agents?action=pmrwc-e',       58000, 1, 23),
      ('agents?action=pmrwc-x',       58000, 1, 23),
      ('agents?action=views',         59000, 1, 23),
      ('agents?action=pmrw-select',  290000, 5, 23),
      ('agents?action=pmrwc-select', 290000, 5, 23),
      ('snapshot-record',             25000, 5, 23),
      ('overnight-record',             9000, 5, 9)
    ) as call(path, timeout_ms, every_minutes, last_utc_hour)
    where extract(minute from now() at time zone 'utc')::int % call.every_minutes = 0
      and extract(hour from now() at time zone 'utc')::int <= call.last_utc_hour;
  $cron$
);
