-- Reconciliation placeholder. Intentionally contains no DDL.
--
-- `0023_t212_orders.sql` was applied out of band through the Supabase
-- MCP connector, which recorded version `20260818044126` in
-- `supabase_migrations.schema_migrations` in addition to `0023`.
-- Without a local file carrying that version, `supabase db push`
-- refuses to run:
--
--     Remote migration versions not found in local migrations directory.
--
-- This file is the local half of that pair. `db push` matches on the
-- version prefix, sees `20260818044126` already recorded remotely, and
-- skips it — which is correct, because its DDL did run. On a FRESH
-- database it executes as a no-op; `0023` sorts ahead of it and
-- creates the tables.
--
-- While `migrations.yml` owns `db push`, apply migrations by pushing
-- the file to main and nothing else.
